name: 'Dependency Review'
on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Checkout the Repo"
        
  dependency-review:
    uses: CanarysPlayground/GHAS-Reusable/.github/workflows/dependency-review.yml@main
    
