name: 'Dependency Review'
on: 
  pull_request:
    branches:
      - main

jobs:      
  dependency-review:
    uses: CanarysPlayground/GHAS-Reusable/.github/workflows/dependency-review.yml@main
    
