name: PaC-appAuth

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  pac-appAuth:
    runs-on: ubuntu-latest

    steps:
      # - uses: tibdex/github-app-token@v1
      #   id: get-token
      #   with:
      #     private_key: ${{ secrets.gh_app_private_key }}
      #     app_id: ${{ secrets.gh_app_id }}
          
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          
      - name: Debug Token (Masked)
        # run: echo "Token is of length:${#${{ secrets.admin_token }}}"
        run: echo "Token is of length:${#${{ steps.get_workflow_token.outputs.token }}}"

      - name: Print Token
        run: echo "Debug Token (Masked):${{ steps.get_workflow_token.outputs.token }}"

      - name: Clone Policy Repository
        run: |
          echo "https://${{ steps.get_workflow_token.outputs.token }}@github.com/CanarysPlayground/GHAS-Reusable.git"
          git clone --branch main --depth 1 "https://${{ steps.get_workflow_token.outputs.token }}@github.com/CanarysPlayground/GHAS-Reusable.git" /tmp/repo
          ls -R /tmp/repo

      - name: Advance Security Compliance Action
        uses: advanced-security/policy-as-code@main
        with:
          severity: error
          policy: CanarysPlayground/GHAS-Reusable
          policy-path: ${{ inputs.policy-path }}
          policy-branch: main
          # token: ${{ secrets.admin_token }}
          token: ${{ steps.get_workflow_token.outputs.token }}
