name: PaC-appAuth

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  pac-appAuth:
    runs-on: ubuntu-latest

    steps:
      # - uses: tibdex/github-app-token@v1
      #   id: get-token
      #   with:
      #     private_key: ${{ secrets.APP_ID }}
      #     app_id: ${{ secrets.APP_KEY }}
          
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_KEY }}

      - name: Advance Security Compliance Action
        uses: advanced-security/policy-as-code@main
        with:
          severity: error
          policy: CanarysPlayground/GHAS-Reusable
          policy-path: ${{ inputs.policy-path }}
          policy-branch: main
          # token: ${{ secrets.admin_token }}
          token: ${{ steps.get_workflow_token.outputs.token }}
