name: Policy-as-Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  policy-as-code:
    uses: CanarysPlayground/GHAS_Reusable/.github/workflows/policy-as-code.yml@main
    with:
      admin_token: ${{ secrets.ADMIN_TOKEN }}
