name: PaC

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  policy-as-code:
    runs-on: ubuntu-latest

    steps:
    # Policy as Code
    - name: Advance Security Policy as Code
      uses: advanced-security/policy-as-code@v2.7.3
